import pandas as pd
import numpy as np
from prophet import Prophet
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import os

# Load the aggregated monthly overall data generated by run_model_computation_start.py
data_path = "outputs/model_computation_start_20260623/mart_monthly_overall.csv"
if not os.path.exists(data_path):
    print(f"Error: {data_path} not found.")
    exit(1)

df = pd.read_csv(data_path)

# Prepare data for time series
# Assuming columns: 'period' (YYYY-MM), 'quantity'
df['ds'] = pd.to_datetime(df['period'] + '-01')
df['y'] = df['quantity'].astype(float)
df = df.sort_values('ds').reset_index(drop=True)

# Train-Test Split (last 12 months for testing, which would be 2025)
train_df = df.iloc[:-12].copy()
test_df = df.iloc[-12:].copy()

print(f"Train periods: {train_df['period'].min()} to {train_df['period'].max()} ({len(train_df)} months)")
print(f"Test periods:  {test_df['period'].min()} to {test_df['period'].max()} ({len(test_df)} months)")
print("-" * 50)

# Helper for metrics
def calculate_metrics(y_true, y_pred, name):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    
    # MAPE with safety for zero true values
    safe_y_true = np.where(y_true == 0, 1e-10, y_true)
    mape = np.mean(np.abs((y_true - y_pred) / safe_y_true)) * 100
    
    print(f"Model: {name}")
    print(f"  MAE:  {mae:,.2f}")
    print(f"  RMSE: {rmse:,.2f}")
    print(f"  MAPE: {mape:,.2f}%")
    print("-" * 50)

# 1. Prophet Model
m = Prophet(yearly_seasonality=True, weekly_seasonality=False, daily_seasonality=False)
m.fit(train_df[['ds', 'y']])

future = test_df[['ds']].copy()
forecast = m.predict(future)
test_df['prophet_pred'] = forecast['yhat'].values

# Calculate Metrics for Prophet
calculate_metrics(test_df['y'].values, test_df['prophet_pred'].values, "Prophet (Sales Only)")

# 2. XGBoost Model (with lag features)
# Create lag features (e.g., lag 1, lag 2, lag 12)
df_xgb = df[['ds', 'y', 'period']].copy()
df_xgb['month'] = df_xgb['ds'].dt.month
df_xgb['lag_1'] = df_xgb['y'].shift(1)
df_xgb['lag_2'] = df_xgb['y'].shift(2)
df_xgb['lag_12'] = df_xgb['y'].shift(12)

# Drop NaNs from lag creation
df_xgb = df_xgb.dropna().reset_index(drop=True)

train_xgb = df_xgb[df_xgb['ds'] < test_df['ds'].min()].copy()
test_xgb = df_xgb[df_xgb['ds'] >= test_df['ds'].min()].copy()

# Features
features = ['month', 'lag_1', 'lag_2', 'lag_12']
X_train = train_xgb[features]
y_train = train_xgb['y']
X_test = test_xgb[features]
y_test = test_xgb['y']

xgb_model = XGBRegressor(n_estimators=100, max_depth=3, learning_rate=0.1, random_state=42)
xgb_model.fit(X_train, y_train)

test_xgb['xgb_pred'] = xgb_model.predict(X_test)

# Calculate Metrics for XGBoost
calculate_metrics(test_xgb['y'].values, test_xgb['xgb_pred'].values, "XGBoost (Sales History with Lags)")

