import { test, expect } from '@playwright/test'
import path from 'node:path'
import { readFile } from 'node:fs/promises'
import { MEDSHIELD_MARKUP, MEDSHIELD_STYLE } from '../lib/medshieldReference'
import { getExecutableDashboardScript } from '../services/api/dashboard-engine'

test('area ranking keeps buyer ownership separate from mapped geography', async ({ page }) => {
  await page.route('http://medshield.test/**', route => route.fulfill({contentType:'text/html',body:'<html><body></body></html>'}))
  await page.goto('http://medshield.test/')
  await page.setContent(`<style>${MEDSHIELD_STYLE}</style>${MEDSHIELD_MARKUP}`)
  await page.evaluate(()=>{window.fetch=async()=>new Response('{}',{status:503})})
  await page.addScriptTag({path:path.resolve('node_modules/chart.js/dist/chart.umd.js')})
  await page.evaluate(script=>new Function(script)(),getExecutableDashboardScript())
  await page.evaluate(()=>{
    const app=window as any
    app.setDescriptivePeriod('custom');app.setYear('2025');app.showPage('territory')
    const row=(sector:string,channel:string,territory:string,revenue:number,quantity:number,period='2025-01',product='A')=>({sector,channel,territory,revenue,quantity,period,product,row_count:1,basis:'Test fixture'})
    app.setSalesSectorsData({rows:[row('Government','Unclassified channel','Quezon',1000,10),row('Private','Hospital','Quezon',100,90),row('Private','Pharma','Batangas',300,10),row('Private','Hospital','Quezon',200,20,'2024-01'),row('Unknown','Hospital','Unassigned geography',500,30),row('Internal','Internal','Unassigned geography',50,5),row('Private','Pharma','Batangas',900,100,'2025-01','B')],source:{file:'test fixture',excluded:{}}})
  })
  await expect(page.locator('#growthChart')).not.toBeVisible()
  await expect(page.locator('#revenueHeatmapGrid')).not.toBeVisible()
  await page.selectOption('#sectorCluster','Private')
  await page.selectOption('#sectorProduct','A')
  await page.evaluate(()=>(window as any).setYear('2025'))
  await expect(page.locator('#sectorProfileTable')).toContainText('Batangas')
  await expect(page.locator('#sectorProfileTable')).toContainText('Quezon')
  await expect(page.locator('#sectorProfileTable')).toContainText('Private 100.0%')
  const series=()=>page.evaluate(()=>(window as any).Chart.getChart(document.getElementById('sectorRevenueChart')).data.datasets[0].data)
  expect(await series()).toEqual([300,100])
  await page.selectOption('#sectorCluster','Unknown')
  await expect(page.locator('#sectorStatus')).toContainText('No mapped area')
  await expect(page.locator('#areaMappingCoverage')).toHaveText('0.0% mapped')
  await page.selectOption('#sectorCluster','All')
  await expect(page.locator('#sectorProfileTable')).not.toContainText('Unassigned geography')
  await page.screenshot({path:'test-results/section-4-sectors.png',fullPage:true})
  await page.evaluate(()=>(window as any).setYear('2022'))
  await expect(page.locator('#sectorStatus')).toContainText('No mapped area')
  await page.evaluate(()=>(window as any).setSalesSectorsData(null,'Service unavailable'))
  await expect(page.locator('#sectorProfileTable')).toBeEmpty()
  await expect(page.locator('#sectorStatus')).toHaveText('Service unavailable')
})

test('product prioritization follows trailing periods and custom-range monthly granularity', async ({ page }) => {
  await page.route('http://medshield.test/**', route => route.fulfill({contentType:'text/html',body:'<html><body></body></html>'}))
  await page.goto('http://medshield.test/')
  await page.setContent(`<style>${MEDSHIELD_STYLE}</style>${MEDSHIELD_MARKUP}`)
  await page.evaluate(()=>{window.fetch=async()=>new Response('{}',{status:503})})
  await page.addScriptTag({path:path.resolve('node_modules/chart.js/dist/chart.umd.js')})
  await page.evaluate(script=>new Function(script)(),getExecutableDashboardScript())
  await page.evaluate(()=>{
    const app=window as any,row=(product:string,period:string,revenue:number)=>({date:period+'-28',sector:'Private',channel:'Pharma',territory:'Quezon',revenue,quantity:10,period,product,row_count:1,basis:'fixture'})
    const currentRows=Array.from({length:30},(_,index)=>row('Product '+String(index+1).padStart(2,'0'),'2025-02',3000-index*50))
    const priorRows=Array.from({length:10},(_,index)=>row('Prior Product '+String(index+1).padStart(2,'0'),'2024-06',10000-index*500))
    app.setSalesSectorsData({rows:[...currentRows,...priorRows],source:{file:'fixture',excluded:{}}})
    app.showPage('products');app.setDescriptivePeriod('custom');app.setYear('2025')
  })
  await expect(page.locator('#btnYoyYear')).toHaveCount(0)
  expect(await page.evaluate(()=>(window as any).Chart.getChart(document.getElementById('productBarChart')).data.datasets.map((d:any)=>[d.label,d.type||'bar']))).toEqual([['Net sales revenue','bar'],['Cumulative portfolio revenue (%)','line']])
  expect(await page.evaluate(()=>(window as any).Chart.getChart(document.getElementById('productBarChart')).data.labels.length)).toBe(2)
  expect(await page.evaluate(()=>(window as any).Chart.getChart(document.getElementById('paretoCurveChart')).data.datasets.length)).toBe(2)
  await expect(page.locator('#productPriorityScope')).toContainText('2 of 30 positive-revenue products')
  await expect(page.locator('#productPriorityScope')).toContainText('All focus-cohort products are shown')
  await expect(page.locator('#productPriorityScope')).toContainText('linear programming')
  await expect(page.locator('#productTable tbody tr')).toHaveCount(2)
  await expect(page.locator('#abcChart').locator('xpath=ancestor::div[contains(@class,"chart-card")]').locator('.chart-title')).toHaveText('Top 5% Cohort Revenue Contribution')
  expect(await page.evaluate(()=>(window as any).Chart.getChart(document.getElementById('abcChart')).data.labels)).toEqual([
    'Top 5% cohort · 8.72% of revenue',
    'Remaining 95% · 91.28% of revenue',
  ])
  await page.selectOption('#productCohortSelect','10')
  await expect(page.locator('#productPriorityScope')).toContainText('3 of 30 positive-revenue products')
  await expect(page.locator('#productTable tbody tr')).toHaveCount(3)
  await expect(page.locator('#abcChart').locator('xpath=ancestor::div[contains(@class,"chart-card")]').locator('.chart-title')).toHaveText('Top 10% Cohort Revenue Contribution')
  expect(await page.evaluate(()=>(window as any).Chart.getChart(document.getElementById('productBarChart')).data.labels.length)).toBe(3)
  await page.selectOption('#productCohortSelect','20')
  await expect(page.locator('#productPriorityScope')).toContainText('6 of 30 positive-revenue products')
  await expect(page.locator('#productTable tbody tr')).toHaveCount(6)
  await expect(page.locator('#abcChart').locator('xpath=ancestor::div[contains(@class,"chart-card")]').locator('.chart-title')).toHaveText('Top 20% Cohort Revenue Contribution')
  expect(await page.evaluate(()=>(window as any).Chart.getChart(document.getElementById('productBarChart')).data.labels.length)).toBe(6)
  expect(await page.evaluate(()=>(window as any).Chart.getChart(document.getElementById('paretoCurveChart')).data.labels)).toEqual(['Jan 25','Feb 25','Mar 25','Apr 25','May 25','Jun 25','Jul 25','Aug 25','Sep 25','Oct 25','Nov 25','Dec 25'])
  await page.evaluate(()=>(window as any).setCustomDateRange('2024-01-01','2024-12-31'))
  await expect(page.locator('#productPriorityScope')).toContainText('2 of 10 positive-revenue products')
  expect(await page.evaluate(()=>(window as any).Chart.getChart(document.getElementById('productBarChart')).data.labels)).toEqual(['Prior Product 01','Prior Product 02'])
  await expect(page.locator('#productTable tbody tr')).toHaveCount(2)
  await page.selectOption('#descriptivePeriodSelect','3')
  await expect.poll(()=>page.evaluate(()=>(window as any).Chart.getChart(document.getElementById('paretoCurveChart')).data.labels.length)).toBe(3)
  await expect(page.locator('#productPriorityScope')).toContainText('positive-revenue products')
  await page.selectOption('#descriptivePeriodSelect','6')
  await expect.poll(()=>page.evaluate(()=>(window as any).Chart.getChart(document.getElementById('paretoCurveChart')).data.labels.length)).toBe(6)
  await page.selectOption('#descriptivePeriodSelect','all')
  const allTime = await page.evaluate(()=>{
    const chart=(window as any).Chart.getChart(document.getElementById('paretoCurveChart'))
    return {labels:chart.data.labels,axisTitle:chart.options.scales.x.title.text}
  })
  expect(allTime.labels).toContain('2024')
  expect(allTime.labels).toContain('2025')
  expect(allTime.labels.every((label:string)=>/^\d{4}(?: (?:YTD|Partial))?$/.test(label))).toBe(true)
  expect(allTime.axisTitle).toBe('Year')
  await expect(page.locator('#productPriorityScope')).toContainText('All Time')
  await page.selectOption('#descriptivePeriodSelect','30d')
  await expect.poll(()=>page.evaluate(()=>(window as any).Chart.getChart(document.getElementById('paretoCurveChart')).data.labels.length)).toBe(30)
  await page.selectOption('#descriptivePeriodSelect','custom')
  await page.evaluate(()=>(window as any).setCustomDateRange('2024-06-01','2024-06-30'))
  await expect(page.locator('#productPriorityScope')).toContainText('2 of 10 positive-revenue products')
  await expect(page.locator('#productTable tbody tr')).toHaveCount(2)
})

test('last 30 days anchors to the current date backwards and keeps missing days as gaps', async ({ page }) => {
  await page.route('http://medshield.test/**', route => route.fulfill({contentType:'text/html',body:'<html><body></body></html>'}))
  await page.goto('http://medshield.test/')
  await page.setContent(`<style>${MEDSHIELD_STYLE}</style>${MEDSHIELD_MARKUP}`)
  await page.evaluate(()=>{window.fetch=async()=>new Response('{}',{status:503})})
  await page.addScriptTag({path:path.resolve('node_modules/chart.js/dist/chart.umd.js')})
  await page.evaluate(script=>new Function(script)(),getExecutableDashboardScript())
  await page.evaluate(()=>{
    const app=window as any
    const today = new Intl.DateTimeFormat('en-CA', {
      timeZone: 'Asia/Manila', year: 'numeric', month: '2-digit', day: '2-digit'
    }).format(new Date())
    app.setDescriptivePeriod('30d')
    app.setSalesSectorsData({rows:[{date:today,period:today.slice(0,7),product:'A',sector:'Private',channel:'Pharma',territory:'Quezon',revenue:500,quantity:10,row_count:1,basis:'fixture'}],source:{file:'fixture',excluded:{}}})
  })
  const chart=await page.evaluate(()=>{
    const view=(window as any).Chart.getChart(document.getElementById('overviewBaselineChart'))
    return {labels:view.data.labels,data:view.data.datasets[0].data}
  })
  expect(chart.labels).toHaveLength(30)
  expect(chart.data).toHaveLength(30)
  expect(chart.data.slice(0,29)).toEqual(Array(29).fill(null))
  expect(chart.data[29]).toBe(500)
  await expect(page.locator('#singleYearWrap')).toBeHidden()
})
